--- #YAML:1.0
name:               Net-Gandi
version:            0.7
abstract:           A perl interface to the Gandi XMLRPC API
author:
    - Natal Ngétal <hobbestig@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:          0
    Moose:         0
    Test::More:    0
    XMLRPC::Lite:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
